
services:

  mysql-db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - micro-net

  ai-service:
    build: ./Thaksalawa-AI-AI-Service
    container_name: ai_service
    environment:
      ZILLIZ_URI: ${ZILLIZ_URI}
      ZILLIZ_TOKEN: ${ZILLIZ_TOKEN}
      ZILLIZ_COLLECTION: ${ZILLIZ_COLLECTION}
    ports:
      - "8001:8001"
    depends_on:
      - mysql-db
    networks:
      - micro-net

  user-service:
    build: ./Thaksalawa-AI-Backend
    container_name: user_service
    environment:
      MYSQL_URL: mysql+pymysql://${MYSQL_USER}:${DB_PASSWORD}@mysql-db:3306/${DATABASE_NAME}
    ports:
      - "8002:8002"
    depends_on:
      - mysql-db
    networks:
      - micro-net

volumes:
  mysql_data:

networks:
  micro-net:
